events {}

http {
    include /etc/nginx/mime.types;
    
    upstream auth_upstream {
        server auth:8000;
    }
    upstream api_upstream {
        server api:8000;
    }

    server {
        listen 80;

        # ---------------------------------------------------
        # Added Frontend for Login and Registration Pages

        location / {
            root /usr/share/nginx/html;
            index login.html;
        }

        location = /login {
            root /usr/share/nginx/html;
            try_files /login.html =404;
        }

        location = /register {
            root /usr/share/nginx/html;
            try_files /register.html =404;
        }

        # Auth Service Routes (Matches /register, /login, /auth/docs, etc.)
        location /register {
            proxy_pass http://auth_upstream;
        }
        location /login {
            proxy_pass http://auth_upstream;
        }
        location /auth/ {
            proxy_pass http://auth_upstream;
        }

        # API Service Routes (Matches /logs, /api/docs, etc.)
        location /logs {
            proxy_pass http://api_upstream;
        }
        location /api/ {
            proxy_pass http://api_upstream;
        }
    }
}